# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: West TN Spray Foam | Serving the Mid-South's insulation needs
email: westtnspray@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Specializing in open and closed cell spray foam insulation in and around the Mid-South.  
baseurl: "" # the subpath of your site, e.g. /blog
lang: "en"
url: "https://kaytal.github.io" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
relative_permalinks: false
permalink: /:categories/:title/

# Posts settings
future: true
safe: false
lsi: false
excerpt_separator: "\n\n"


compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all


sass:
  sass_dir: assets/_sass


images: '/assets/images'
